version: "3.1"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: qwerty1234
    ports:
      - 5432:5432
    volumes:
      - ./lab01/db-data:/var/db-data
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db-data:
