version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty1234
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/db-data
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
